server:
  port: 8080
  servlet :
    context-path: /ui
    session:
      cookie:
        name: UISESSION


security:
 
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/rest/hello/principal
